---
- name: ensure nginx is installed
  yum:
    name: nginx
    state: latest

- name: Copy the nginx config files in /etc/nginx/nginx.conf
  template:
    src: ./templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    backup: yes
  notify: 
    - "Start the nginx service for version 7 onward"
    - "Start the nginx service for version 6"
